name: Update Homebrew Formula

on:
  repository_dispatch:
    types:
      - update_formula
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag of the release"
        required: true
        default: ""
      version:
        description: "Version of the release"
        required: true
        default: ""

jobs:
  update-formula:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Public Repository
      - name: Checkout Public Repository
        uses: actions/checkout@v4

      # Step 2: Fetch Tag and Metadata
      - name: Fetch Trigger Data
        run: |
          echo "Fetching release metadata..."
          echo "VERSION=${{ github.event.client_payload.version || github.event.inputs.version }}" >> $GITHUB_ENV
          echo "TAG=${{ github.event.client_payload.tag || github.event.inputs.tag }}" >> $GITHUB_ENV

      # Step 3: Download Release Files
      - name: Download Release Files
        run: |
          mkdir -p dist
          wget "https://raw.githubusercontent.com/rockey5520/snake-game-distributions/main/releases/${{ env.TAG }}/snake-game_${{ env.VERSION }}_darwin_arm64.tar.gz"
          wget "https://raw.githubusercontent.com/rockey5520/snake-game-distributions/main/releases/${{ env.TAG }}/snake-game_${{ env.VERSION }}_darwin_amd64.tar.gz"
          wget "https://raw.githubusercontent.com/rockey5520/snake-game-distributions/main/releases/${{ env.TAG }}/snake-game_${{ env.VERSION }}_linux_arm64.tar.gz"
          wget "https://raw.githubusercontent.com/rockey5520/snake-game-distributions/main/releases/${{ env.TAG }}/snake-game_${{ env.VERSION }}_linux_amd64.tar.gz"

      # Step 4: Calculate SHA256
      - name: Calculate SHA256
        id: calculate_sha
        run: |
         echo "Calculating SHA256 checksums..."
         ls -l dist/
         echo "Contents of dist/snake-game_darwin_arm64.tar.gz:"
         sha256sum dist/snake-game_darwin_arm64.tar.gz
         echo "Contents of dist/snake-game_darwin_amd64.tar.gz:"
         sha256sum dist/snake-game_darwin_amd64.tar.gz
         echo "Contents of dist/snake-game_linux_arm64.tar.gz:"
         sha256sum dist/snake-game_linux_arm64.tar.gz
         echo "Contents of dist/snake-game_linux_amd64.tar.gz:"
         sha256sum dist/snake-game_linux_amd64.tar.gz
    
         SHA_DARWIN_ARM64=$(sha256sum dist/snake-game_darwin_arm64.tar.gz | awk '{print $1}')
         SHA_DARWIN_AMD64=$(sha256sum dist/snake-game_darwin_amd64.tar.gz | awk '{print $1}')
         SHA_LINUX_ARM64=$(sha256sum dist/snake-game_linux_arm64.tar.gz | awk '{print $1}')
         SHA_LINUX_AMD64=$(sha256sum dist/snake-game_linux_amd64.tar.gz | awk '{print $1}')
         echo "sha_darwin_arm64=$SHA_DARWIN_ARM64" >> $GITHUB_ENV
         echo "sha_darwin_amd64=$SHA_DARWIN_AMD64" >> $GITHUB_ENV
         echo "sha_linux_arm64=$SHA_LINUX_ARM64" >> $GITHUB_ENV
         echo "sha_linux_amd64=$SHA_LINUX_AMD64" >> $GITHUB_ENV
         echo "SHA256 for darwin_arm64: $SHA_DARWIN_ARM64"
         echo "SHA256 for darwin_amd64: $SHA_DARWIN_AMD64"
         echo "SHA256 for linux_arm64: $SHA_LINUX_ARM64"
         echo "SHA256 for linux_amd64: $SHA_LINUX_AMD64"

      # Step 5: Update Homebrew Formula
      - name: Update Formula
        run: |
          FORMULA_FILE=Formula/snake-game.rb
          sed -i "s/version \".*\"/version \"${{ env.VERSION }}\"/" $FORMULA_FILE
          sed -i "s|url .*darwin_arm64.*|url \"https://raw.githubusercontent.com/rockey5520/snake-game-distributions/main/releases/${{ env.TAG }}/snake-game_${{ env.VERSION }}_darwin_arm64.tar.gz\"|" $FORMULA_FILE
          sed -i "s/sha256 \".*\"/sha256 \"${{ env.sha_darwin_arm64 }}\"/" $FORMULA_FILE
          sed -i "s|url .*darwin_amd64.*|url \"https://raw.githubusercontent.com/rockey5520/snake-game-distributions/main/releases/${{ env.TAG }}/snake-game_${{ env.VERSION }}_darwin_amd64.tar.gz\"|" $FORMULA_FILE
          sed -i "s/sha256 \".*\"/sha256 \"${{ env.sha_darwin_amd64 }}\"/" $FORMULA_FILE
          sed -i "s|url .*linux_arm64.*|url \"https://raw.githubusercontent.com/rockey5520/snake-game-distributions/main/releases/${{ env.TAG }}/snake-game_${{ env.VERSION }}_linux_arm64.tar.gz\"|" $FORMULA_FILE
          sed -i "s/sha256 \".*\"/sha256 \"${{ env.sha_linux_arm64 }}\"/" $FORMULA_FILE
          sed -i "s|url .*linux_amd64.*|url \"https://raw.githubusercontent.com/rockey5520/snake-game-distributions/main/releases/${{ env.TAG }}/snake-game_${{ env.VERSION }}_linux_amd64.tar.gz\"|" $FORMULA_FILE
          sed -i "s/sha256 \".*\"/sha256 \"${{ env.sha_linux_amd64 }}\"/" $FORMULA_FILE

      # Step 6: Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Formula/snake-game.rb
          git commit -m "Update formula for version ${{ env.VERSION }}"
          git push
